import os


TOKEN_LIFE_TIME=int(os.getenv("TOKEN_LIFE_TIME"))

ACCESS_TOKEN_EXPIRE_MINUTES = 3660  # 1 hour

REFRESH_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7 # 7 days

ALGORITHM = "HS256"

JWT_SECRET_KEY = os.environ['JWT_SECRET_KEY']

JWT_REFRESH_SECRET_KEY = os.environ['JWT_REFRESH_SECRET_KEY']

TEMPLATES_PATH = "templates"

STORAGE_PATH = "storage"

SETTLEMENT_HOSTEL_PATH = STORAGE_PATH + "/settlement_hostel"

DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
